

/*
--20130723.lishengming
  1.由于账户层不作清算只作同步，股份表中的费用、以及当日交易相关字段无法得到，因此予以去掉；
    去掉这些字段后，为了保证正常的初始化增加当前成本和当前累计收益字段。
  2.委托表中委托序号不作为主键，改成和子账户一起作为联合主键。
  3.资金流水和成交流水合并，去掉资金流水表，相关的字段增加到成交表中。
  
--20130719.lishengming
  1.去掉委托序号和委托批号Sequence。
  2.增加自定义序列表。
  
--20130716.lishengming
  1.账户表增加账户名称、资金密码、交易密码2个字段。原fund_code中文名称改为“资金账户代码”对应实际的营业部资金账户。
  2.去掉资金账户表（cashaccount）。
  3.子账户表增加子账户名称字段。
      
--20130705,lishengming
  1.子账户表增加账户操作状态和独占人员字段。  
  
--20130626,lishengming
  1.子账户资金表和委托表中增加预买费用和预卖费用字段，委托表中还增加预买金额字段。
    注意：可用计算时需要扣除掉预买费用，即：可用余额=当前余额 - 预买金额 - 预买费用。
  2.菜单表增加上级菜单序号、所属模块以及菜单地址三个字段。
  3.菜单附加权限表增加附加权限地址字段。  
  
--20130625,lishengming
  1.资金流水表及其历史表去掉busin_class字段，增加委托方向和业务类别代码字段(businclass_code)。
  2.批号Sequence拆分成两个：委托批号Seq(seq_entrust_batchid)和资金流水批号Seq(seq_casflow_batchid)。
  
--20130619,lishengming
  1.增加股东账户表。
  2.增加资金账户表。
  3.委托表增加MAC地址和IP地址字段。
  4.增加SEQUENCE：批号、委托序号、成交序号、资金流水序号、操作日志流水号。

--20130619,lishengming
	1.增加操作员角色表。
	2.角色表增加所属机构字段。
	3.菜单表增加适用范围和备注字段。
	4.菜单附加权限表增加备注字段。
	5.增加人员账户权限表。
	
--20130614,lishengming
	1.去掉账户表中的机构名称字段。
 
 --20130613,lishengming	
	1.账户表(fund)增加字段fund_id，并设置为主键。
	2.证券类别表(stocktype)和委托方向表（entrustdirection）中去掉交易市场字段（market_code）。
	3.系统信息表名由tsysteminfo改成systeminfo。
  4.增加交易日表（tradedate）。
	5.交易市场表(market)中增加日历字段(calendar)，OPEN_TIME_AFERNOON更名为OPEN_TIME_AFTERNOON。
	6.证券类别表AMONT_PER_HAND更名为AMOUNT_PER_HAND。
	7.数据字典表(dictionary)主键增加词条代码(entry_code)。
	
 
 create by andr,20130612 先判断表是否存在，如果存在就不处理，如果不存在则创建表
 */
 


PROMPT crate tables start...

/* 归档配置表 */
PROMPT
PROMPT create table ARCHIVECONFIG ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('ARCHIVECONFIG');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE ARCHIVECONFIG  (
  TABLE_NAME          NUMBER(10) NOT NULL ,
  ARCHIVE_TYPE        NUMBER(10) NOT NULL ,
  ARCHIVE_WAY         VARCHAR2(4000),
  ARCHIVE_BY_FUND  CHAR(1)    NOT NULL ,
  CONSTRAINT PK_ARCHIVECONFIG PRIMARY KEY (TABLE_NAME)
)
	';  
	END IF;
end;
/ 

/* 营业部表 */
PROMPT
PROMPT create table BROKEROFFICE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('BROKEROFFICE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE BROKEROFFICE  (
  BROKEROFFICE_CODE   VARCHAR2(16) NOT NULL ,
  BROKEROFFICE_NAME   VARCHAR2(16) NOT NULL ,
  BROKER_CODE         VARCHAR2(32),
  CTS_VERSION         VARCHAR2(16),
  REMARK              VARCHAR2(256),
  CONSTRAINT PK_BROKEROFFICE PRIMARY KEY (BROKEROFFICE_CODE)
)
	'; 
	END IF; 
end;
/ 

/* 成交表 */
PROMPT
PROMPT create table BUSINESS ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('BUSINESS');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE BUSINESS  (
  BUSIN_DATE          NUMBER(8)  NOT NULL ,
  BATCHOP_ID          NUMBER(10) NOT NULL ,
  BUSINESS_ID         NUMBER(10) NOT NULL ,
  BUSINCLASS_CODE     CHAR(1)    NOT NULL ,  
  FUND_ID             NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  COMBI_CODE          VARCHAR2(64) ,
  STOCK_CODE          VARCHAR2(32) ,
  BALANCE             NUMBER(20,4) ,
  CURRENT_CASH        NUMBER(20,4) ,
  BUSINESS_AMOUNT     NUMBER(10),
  CURRENT_AMOUNT      NUMBER(10),  
  BUSINESS_PRICE      NUMBER(16,8),  
  BUSINESS_TIME       NUMBER(6),
  ENTRUST_ID          NUMBER(10),
  ENTRUSTDIRECTION_CODE NUMBER(4),  
  JY_FEE              NUMBER(20,4),
  JS_FEE              NUMBER(20,4),
  YH_FEE              NUMBER(20,4),
  GH_FEE              NUMBER(20,4),
  QT_FEE              NUMBER(20,4),
  YJ_FEE              NUMBER(20,4),
  JG_FEE              NUMBER(20,4),
  ZG_FEE              NUMBER(20,4),
  JS2_FEE             NUMBER(20,4),
  OPERATOR_ID         NUMBER(10),
  TIMESTAMP           TIMESTAMP,
  SUMMARY             VARCHAR2(4000),
  CONSTRAINT PK_BUSINESS PRIMARY KEY (BUSINESS_ID)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISBUSINESS ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISBUSINESS');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISBUSINESS  (
  BUSIN_DATE          NUMBER(8),
  BUSINESS_ID         NUMBER(10) NOT NULL ,
  ENTRUST_ID          NUMBER(10),
  UNIT_ID             NUMBER(10),
  COMBI_CODE          VARCHAR2(64) NOT NULL ,
  STOCK_CODE          VARCHAR2(32),
  ENTRUSTDIRECTION_CODE NUMBER(4),
  BUSINESS_PRICE      NUMBER(16,8),
  BUSINESS_AMOUNT     NUMBER(10),
  BUSINESS_TIME       NUMBER(6),
  JY_FEE              NUMBER(20,4),
  JS_FEE              NUMBER(20,4),
  YH_FEE              NUMBER(20,4),
  GH_FEE              NUMBER(20,4),
  QT_FEE              NUMBER(20,4),
  YJ_FEE              NUMBER(20,4),
  JG_FEE              NUMBER(20,4),
  ZG_FEE              NUMBER(20,4),
  JS2_FEE             NUMBER(20,4),
  OPERATOR_ID         NUMBER(10),
  TIMESTAMP           TIMESTAMP,
  CONSTRAINT PK_HISBUSINESS PRIMARY KEY (BUSIN_DATE，BUSINESS_ID)
)
	'; 
	END IF; 
end;
/ 

/* 业务授权表 */
PROMPT
PROMPT create table BUSINESSAUTHORIZATION ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('BUSINESSAUTHORIZATION');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE BUSINESSAUTHORIZATION  (
  AUTHORIZATION_OBJECT CHAR(1) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  ALLOWED_STOCKTYPES  VARCHAR2(4000),
  ALLOWED_ENTRUSTDIRECTIONS VARCHAR2(4000),
  ALLOWED_MARKETS     VARCHAR2(4000),
  CONSTRAINT PK_BUSINESSAUTHORIZATION PRIMARY KEY (AUTHORIZATION_OBJECT,INSTITUTION_ID,FUND_ID,UNIT_ID,OPERATOR_ID)
)
	';  
	END IF;
end;
/ 

/* 资金流水表 */
/*
PROMPT
PROMPT create table CASHFLOW ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('CASHFLOW');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE CASHFLOW  (
  BUSIN_DATE          NUMBER(8),
  BATCHOP_ID          NUMBER(10) NOT NULL ,
  CASHFLOW_ID         NUMBER(10) NOT NULL ,
  BUSINCLASS_CODE       NUMBER(4)  NOT NULL,
  OPERATOR_ID         NUMBER(10),
  BUSINESS_ID         NUMBER(10) NOT NULL ,
  ENTRUST_ID          NUMBER(10),
  FUND_ID             NUMBER(10),
  UNIT_ID             NUMBER(10),
  COMBI_CODE          VARCHAR2(64) NOT NULL , 
  ENTRUSTDIRECTION_CODE NUMBER(4), 
  CURRENCY_CODE       CHAR(3),
  BALANCE             NUMBER(20,4),
  CURRENT_CASH        NUMBER(20,4),
  STOCK_CODE          VARCHAR2(32),
  AMOUNT              NUMBER(10),
  CURRENT_AMOUNT      NUMBER(10),
  SUMMARY             VARCHAR2(4000),
  TIME                VARCHAR2(32),
  TIMESTAMP           TIMESTAMP,
  CONSTRAINT PK_CASHFLOW PRIMARY KEY (CASHFLOW_ID)
)
	';  
	END IF;
end;
/ 
*/
/*
PROMPT
PROMPT create table HISCASHFLOW ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISCASHFLOW');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISCASHFLOW  (
  BUSIN_DATE          NUMBER(8),
  BATCHOP_ID          NUMBER(10) NOT NULL ,
  CASHFLOW_ID         NUMBER(10) NOT NULL ,
  BUSINCLASS_CODE       NUMBER(4)  NOT NULL,
  OPERATOR_ID         NUMBER(10),
  BUSINESS_ID         NUMBER(10) NOT NULL ,
  ENTRUST_ID          NUMBER(10),
  FUND_ID             NUMBER(10),
  UNIT_ID             NUMBER(10),
  COMBI_CODE          VARCHAR2(64) NOT NULL ,  
  ENTRUSTDIRECTION_CODE NUMBER(4),
  CURRENCY_CODE       CHAR(3),
  BALANCE             NUMBER(20,4),
  CURRENT_CASH        NUMBER(20,4),
  STOCK_CODE          VARCHAR2(32),
  AMOUNT              NUMBER(10),
  CURRENT_AMOUNT      NUMBER(10),
  SUMMARY             VARCHAR2(4000),
  TIME                VARCHAR2(32),
  TIMESTAMP           TIMESTAMP,
  CONSTRAINT PK_HISCASHFLOW PRIMARY KEY (BUSIN_DATE,CASHFLOW_ID)
)
	';  
	END IF;
end;
/ 
*/

/* 组合股份表 */
PROMPT
PROMPT create table COMBISTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('COMBISTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE COMBISTOCK  (
  BUSIN_DATE          NUMBER(8),
  UNIT_ID             NUMBER(10) NOT NULL ,
  COMBI_CODE          VARCHAR2(64) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  CURRENT_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_AMOUNT       NUMBER(16) NOT NULL ,
  PRESALE_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  BUY_AMOUNT          NUMBER(16) NOT NULL ,
  SALE_AMOUNT         NUMBER(16) NOT NULL ,
  BUY_BALANCE         NUMBER(20,4) NOT NULL ,
  SALE_BALANCE        NUMBER(20,4) NOT NULL ,
  BUY_FEE             NUMBER(20,4) NOT NULL ,
  SALE_FEE            NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_COMBISTOCK PRIMARY KEY (UNIT_ID,COMBI_CODE,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISCOMBISTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISCOMBISTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISCOMBISTOCK  (
  BUSIN_DATE          NUMBER(8),
  UNIT_ID             NUMBER(10) NOT NULL ,
  COMBI_CODE          VARCHAR2(64) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  CURRENT_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_AMOUNT       NUMBER(16) NOT NULL ,
  PRESALE_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  BUY_AMOUNT          NUMBER(16) NOT NULL ,
  SALE_AMOUNT         NUMBER(16) NOT NULL ,
  BUY_BALANCE         NUMBER(20,4) NOT NULL ,
  SALE_BALANCE        NUMBER(20,4) NOT NULL ,
  BUY_FEE             NUMBER(20,4) NOT NULL ,
  SALE_FEE            NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_HISCOMBISTOCK PRIMARY KEY (BUSIN_DATE,UNIT_ID,COMBI_CODE,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 

/* 配置参数定义表 */
PROMPT
PROMPT create table CONFIGPARAMETERDEFINE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('CONFIGPARAMETERDEFINE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE CONFIGPARAMETERDEFINE  (
  PARAMETER_ID        NUMBER(10) NOT NULL ,
  PARAMETER_NAME      VARCHAR2(128),
  ACTION_RANGE        CHAR(1),
  TYPE                CHAR(1),
  VALUE_RANGE         VARCHAR2(4000),
  MULTI_CHOICE        CHAR(1),
  DEFAULT_VALUE       VARCHAR2(4000),
  GROUP_L1            VARCHAR2(32),
  GROUP_L2            VARCHAR2(32),
  DISPLAY_ORDER       NUMBER(10),
  EDITABLE            CHAR(1),
  ENCRYPT             CHAR(1),
  CONSTRAINT PK_CONFIGPARAMETERDEFINE PRIMARY KEY (PARAMETER_ID)
)
	';  
	END IF;
end;
/ 

/* 配置参数设置表 */
PROMPT
PROMPT create table CONFIGPARAMETERSET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('CONFIGPARAMETERSET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE CONFIGPARAMETERSET  (
  PARAMETER_ID        NUMBER(10) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  VALUE               VARCHAR2(4000),
  CONSTRAINT PK_CONFIGPARAMETERSET PRIMARY KEY (PARAMETER_ID,INSTITUTION_ID)
)
	';  
	END IF;
end;
/ 

/* 数据字典表 */
PROMPT
PROMPT create table DICTIONARY ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('DICTIONARY');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE DICTIONARY  (
  DICTIONARY_ID       NUMBER(10) NOT NULL ,
  ENTRY_CODE          CHAR(1) NOT NULL ,
  ENTRY_NAME          VARCHAR2(256) NOT NULL ,
  CONSTRAINT PK_DICTIONARY PRIMARY KEY (DICTIONARY_ID,ENTRY_CODE)
)
	';  
	END IF;
end;
/ 

/* 委托表 */
PROMPT
PROMPT create table ENTRUST ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('ENTRUST');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE ENTRUST  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  BATCHOP_ID          NUMBER(10) NOT NULL ,
  ENTRUST_ID          NUMBER(10) NOT NULL ,
  REPORT_ID           NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  COMBI_CODE          VARCHAR2(64) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  ENTRUSTDIRECTION_CODE NUMBER(4) NOT NULL ,
  PRICE_TYPE          CHAR(1) NOT NULL ,
  PRICE               NUMBER(16,8) NOT NULL ,
  AMOUNT              NUMBER(10) NOT NULL ,
  BALANCE             NUMBER(20,4) NOT NULL ,
	PREBUY_BALANCE      NUMBER(20,4) NOT NULL , 
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  PREBUY_FEE          NUMBER(20,4) NOT NULL ,
  PRESALE_FEE          NUMBER(20,4) NOT NULL ,  
  PREBUY_FROZEN_BALANCE NUMBER(20,4) NOT NULL ,  
  ENTRUST_STATUS      CHAR(1) NOT NULL ,
  ENTRUST_TIME        NUMBER(6) NOT NULL ,
  CANCEL_FLAG         CHAR(1) NOT NULL ,
  CANCEL_ID           NUMBER(10) NOT NULL ,
  CANCEL_AMOUNT       NUMBER(10) NOT NULL ,
  BUSINESS_AMOUNT     NUMBER(10) NOT NULL ,
  BUSINESS_BALANCE    NUMBER(20,4) NOT NULL ,
  REMARKS             VARCHAR2(256),
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  TIMESTAMP           TIMESTAMP NOT NULL ,
  IP                  VARCHAR2(32),
  MAC                 VARCHAR2(32),
  CONSTRAINT PK_ENTRUST PRIMARY KEY (UNIT_ID,ENTRUST_ID)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISENTRUST ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISENTRUST');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISENTRUST  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  BATCHOP_ID          NUMBER(10) NOT NULL ,
  ENTRUST_ID          NUMBER(10) NOT NULL ,
  REPORT_ID           NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  COMBI_CODE          VARCHAR2(64) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  ENTRUSTDIRECTION_CODE NUMBER(4) NOT NULL ,
  PRICE_TYPE          CHAR(1) NOT NULL ,
  PRICE               NUMBER(16,8) NOT NULL ,
  AMOUNT              NUMBER(10) NOT NULL ,
  BALANCE             NUMBER(20,4) NOT NULL ,
  PREBUY_FROZEN_BALANCE NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  ENTRUST_STATUS      CHAR(1) NOT NULL ,
  ENTRUST_TIME        NUMBER(6) NOT NULL ,
  CANCEL_FLAG         CHAR(1) NOT NULL ,
  CANCEL_ID           NUMBER(10) NOT NULL ,
  CANCEL_AMOUNT       NUMBER(10) NOT NULL ,
  BUSINESS_AMOUNT     NUMBER(10) NOT NULL ,
  BUSINESS_BALANCE    NUMBER(20,4) NOT NULL ,
  REMARKS             VARCHAR2(256),
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  TIMESTAMP           TIMESTAMP NOT NULL ,
  CONSTRAINT PK_HISENTRUST PRIMARY KEY (BUSIN_DATE,UNIT_ID,ENTRUST_ID)
)
	';  
	END IF;
end;
/ 

/* 委托方向表 */
PROMPT
PROMPT create table ENTRUSTDIRECTION ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('ENTRUSTDIRECTION');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE ENTRUSTDIRECTION  (
  ENTRUSTDIRECTION_CODE NUMBER(4) NOT NULL ,
  ENTRUSTDIRECTION_NAME VARCHAR2(16) NOT NULL ,  
  STOCK_DIRECTION     CHAR(1) NOT NULL ,
  FUND_DIRECTION      CHAR(1) NOT NULL ,
  CONSTRAINT PK_ENTRUSTDIRECTION PRIMARY KEY (ENTRUSTDIRECTION_CODE)
)
	';  
	END IF;
end;
/ 

/* 错误代码表 */
PROMPT
PROMPT create table ERRORCODE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('ERRORCODE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE ERRORCODE  (
  ERROR_CODE          NUMBER(10) NOT NULL ,
  ERROR_INFO          VARCHAR2(4000) NOT NULL ,
  CONSTRAINT PK_ERRORCODE PRIMARY KEY (ERROR_CODE)
)
	';  
	END IF;
end;
/ 

/* 费率表 */
PROMPT
PROMPT create table FEE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('FEE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE FEE  (
  ACTION_RANGE        CHAR(1) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  MARKET_CODE         NUMBER(4) NOT NULL ,
  STOCKTYPE_CODE      NUMBER(4) NOT NULL ,
  ENTRUSTDIRECTION_CODE NUMBER(4) NOT NULL ,
  BROKEROFFICE_CODE   VARCHAR2(16) NOT NULL ,
  FEE_TYPE            CHAR(1) NOT NULL ,
  BUSINBALANCE_RATIO  NUMBER(9,8) NOT NULL ,
  FACEVALUE_RATIO     NUMBER(9,8) NOT NULL ,
  FEE_MAX             NUMBER(20,4) NOT NULL ,
  FEE_MIN             NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_FEE PRIMARY KEY (ACTION_RANGE,INSTITUTION_ID,FUND_ID,UNIT_ID,MARKET_CODE,STOCKTYPE_CODE,ENTRUSTDIRECTION_CODE,BROKEROFFICE_CODE,FEE_TYPE)
)
	';  
	END IF;
end;
/ 

/* 账户表 */
PROMPT
PROMPT create table FUND ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('FUND');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE FUND  (
  FUND_ID             NUMBER(10) NOT NULL,
  FUND_NAME           VARCHAR2(64) NOT NULL,
  FUND_CODE           VARCHAR2(32) NOT NULL ,
  FUND_PASSWORD       VARCHAR2(32) NOT NULL,
  TRADE_PASSWORD       VARCHAR2(32) NOT NULL,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,  
  BROKEROFFICE_CODE   VARCHAR2(16) NOT NULL ,
  STATUS              CHAR(1) NOT NULL ,
  REGISTER_DATE       NUMBER(8) NOT NULL ,
  REGISTER_AGENT      NUMBER(10) NOT NULL ,
  CANCEL_DATE         NUMBER(8),
  CANCEL_AGENT        NUMBER(10),
  REMARK              VARCHAR2(256),
  CONSTRAINT PK_FUND PRIMARY KEY (FUND_ID)
)
	';  
	END IF;
end;
/ 

/* 账户资金表 */
PROMPT
PROMPT create table FUNDASSET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('FUNDASSET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE FUNDASSET  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  CURRENCY_CODE       CHAR(3) NOT NULL ,
  BEGIN_CASH          NUMBER(20,4) NOT NULL ,
  CURRENT_CASH        NUMBER(20,4) NOT NULL ,
  INPUT_BALANCE       NUMBER(20,4) NOT NULL ,
  OUTPUT_BALANCE      NUMBER(20,4) NOT NULL ,
  INPUT_TOTAL         NUMBER(20,4) NOT NULL ,
  OUTPUT_TOTAL        NUMBER(20,4) NOT NULL ,
  UNALOT_CASH         NUMBER(20,4),
  CONSTRAINT PK_FUNDASSET PRIMARY KEY (FUND_ID,CURRENCY_CODE)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISFUNDASSET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISFUNDASSET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISFUNDASSET  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  CURRENCY_CODE       CHAR(3) NOT NULL ,
  BEGIN_CASH          NUMBER(20,4) NOT NULL ,
  CURRENT_CASH        NUMBER(20,4) NOT NULL ,
  INPUT_BALANCE       NUMBER(20,4) NOT NULL ,
  OUTPUT_BALANCE      NUMBER(20,4) NOT NULL ,
  INPUT_TOTAL         NUMBER(20,4) NOT NULL ,
  OUTPUT_TOTAL        NUMBER(20,4) NOT NULL ,
  UNALOT_CASH         NUMBER(20,4),
  CONSTRAINT PK_HISFUNDASSET PRIMARY KEY (BUSIN_DATE,FUND_ID,CURRENCY_CODE)
)
	'; 
	END IF; 
end;
/ 

/* 账户股份表 */
PROMPT
PROMPT create table FUNDSTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('FUNDSTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE FUNDSTOCK  (
  BUSIN_DATE          NUMBER(8),
  FUND_ID             NUMBER(10) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  CURRENT_AMOUNT      NUMBER(20) NOT NULL ,
	CURRENT_COST        NUMBER(20,4) NOT NULL ,
	CURRENT_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_FUNDSTOCK PRIMARY KEY (FUND_ID,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISFUNDSTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISFUNDSTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISFUNDSTOCK  (
  BUSIN_DATE          NUMBER(8),
  FUND_ID             NUMBER(10) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_BUYFEE  NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_SALEFEE NUMBER(20,4) NOT NULL ,
  CURRENT_AMOUNT      NUMBER(20) NOT NULL ,
  PREBUY_AMOUNT       NUMBER(16) NOT NULL ,
  PRESALE_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  BUY_AMOUNT          NUMBER(16) NOT NULL ,
  SALE_AMOUNT         NUMBER(16) NOT NULL ,
  BUY_BALANCE         NUMBER(20,4) NOT NULL ,
  SALE_BALANCE        NUMBER(20,4) NOT NULL ,
  BUY_FEE             NUMBER(20,4) NOT NULL ,
  SALE_FEE            NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_HISFUNDSTOCK PRIMARY KEY (BUSIN_DATE,FUND_ID,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 

/* 子账户表 */
PROMPT
PROMPT create table FUNDUNIT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('FUNDUNIT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE FUNDUNIT  (
  UNIT_ID             NUMBER(10) NOT NULL ,
  UNIT_NAME           VARCHAR2(64) NOT NULL,
  UNIT_CODE           VARCHAR2(32) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,  
  STATUS              CHAR(1) NOT NULL ,
  REGISTER_DATE       NUMBER(8) NOT NULL ,
  REGISTER_AGENT      NUMBER(10) NOT NULL ,
  CANCEL_DATE         NUMBER(8),
  CANCEL_AGENT        NUMBER(10),
  REMARK              VARCHAR2(256),
  OP_STATUS           CHAR(1) NOT NULL ,
  EXCLUSIVE_OPERATOR  NUMBER(10),
  CONSTRAINT PK_FUNDUNIT PRIMARY KEY (UNIT_ID)
)
	';  
	END IF;
end;
/ 

/* 机构表 */
PROMPT
PROMPT create table INSTITUTION ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('INSTITUTION');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE INSTITUTION  (
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  INSTITUTION_NAME    VARCHAR2(16) NOT NULL ,
  STATUS              CHAR(1) NOT NULL ,
  REGISTER_DATE       NUMBER(8) NOT NULL ,
  REGISTER_AGENT      NUMBER(10) NOT NULL ,
  CANCEL_DATE         NUMBER(8),
  CANCEL_AGENT        NUMBER(10),
  REMARK              VARCHAR2(256),
  CONSTRAINT PK_INSTITUTION PRIMARY KEY (INSTITUTION_ID)
)
	';  
	END IF;
end;
/ 

/* 机构配额表 */
PROMPT
PROMPT create table INSTITUTIONQUOTA ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('INSTITUTIONQUOTA');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE INSTITUTIONQUOTA  (
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  FUNDCOUNT_LIMIT     NUMBER(10) NOT NULL ,
  UNITCOUNT_LIMIT     NUMBER(10) NOT NULL ,
  OPCOUNT_LIMIT       NUMBER(10) NOT NULL ,
  CONSTRAINT PK_INSTITUTIONQUOTA PRIMARY KEY (INSTITUTION_ID)
)
	'; 
	END IF; 
end;
/ 

/* 交易日表 */
PROMPT
PROMPT create table TRADEDATE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('TRADEDATE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE TRADEDATE  (
  CALENDAR            CHAR(1) NOT NULL,
  NATURAL_DATE				NUMBER(8) NOT NULL ,
  IS_TRADEDATE				CHAR(1) NOT NULL,
  CONSTRAINT PK_TRADEDATE PRIMARY KEY (CALENDAR,NATURAL_DATE)
)
	'; 
	END IF; 
end;
/ 

/* 交易市场表 */
PROMPT
PROMPT create table MARKET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('MARKET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE MARKET  (
  MARKET_CODE         NUMBER(4) NOT NULL ,
  MARKET_NAME         VARCHAR2(16) NOT NULL ,
  CURRENCY_CODE       CHAR(3) NOT NULL ,
  CALENDAR            CHAR(1) NOT NULL,
  OPEN_TIME_MORNING   NUMBER(6) NOT NULL ,
  CLOSE_TIME_MORNING  NUMBER(6) NOT NULL ,
  OPEN_TIME_AFTERNOON  NUMBER(6) NOT NULL ,
  CLOSE_TIME_AFTERNOON NUMBER(6) NOT NULL ,
  OPEN_TIME_NIGHT     NUMBER(6) NOT NULL ,
  CLOSE_TIME_NIGHT    NUMBER(6) NOT NULL ,
  CONSTRAINT PK_MARKET PRIMARY KEY (MARKET_CODE)
)
	'; 
	END IF; 
end;
/ 

/* 菜单表 */
PROMPT
PROMPT create table MENU ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('MENU');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE MENU  (
  MENU_ID             NUMBER(10) NOT NULL ,
  MENU_NAME           VARCHAR2(16) NOT NULL ,
  MODULE              CHAR(1) NOT NULL,
  PARENTMENU_ID       NUMBER(10) NOT NULL ,  
  ACTION_RANGE				CHAR(1) NOT NULL,
  MENU_URL            VARCHAR2(256),
  REMARKS							VARCHAR2(256),
  CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID)
)
	';  
	END IF;
end;
/ 

/* 菜单附加权限表 */
PROMPT
PROMPT create table MENUEXTRARIGHT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('MENUEXTRARIGHT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE MENUEXTRARIGHT  (
  MENU_ID             NUMBER(10) NOT NULL ,
  EXTRARIGHT_CODE     CHAR(1) NOT NULL ,
  EXTRARIGHT_NAME     VARCHAR2(16),
  EXTRARIGHT_URL      VARCHAR2(256),
  REMARKS							VARCHAR2(256),
  CONSTRAINT PK_MENUEXTRARIGHT PRIMARY KEY (MENU_ID,EXTRARIGHT_CODE)
)
	';  
	END IF;
end;
/ 

/* 人员表 */
PROMPT
PROMPT create table OPERATOR ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPERATOR');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPERATOR  (
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  OPERATOR_NAME       VARCHAR2(16) NOT NULL ,
  OPERATOR_PASSWORD   VARCHAR2(64) NOT NULL ,
  PASSWORD_STRENGTH   VARCHAR2(16),
  OPERATOR_TYPE       CHAR(1),
  INSTITUTION_ID      NUMBER(10),
  EMAIL               VARCHAR2(256),
  PHONE_NUMBER        VARCHAR2(256),
  CREDENTIAL_TYPE     CHAR(1),
  CREDENTIAL_NUMBER   VARCHAR2(32),
  PASSWORD_UPDATE_DATE NUMBER(8),
  OPERATOR_STATUS     CHAR(1),
  REGISTER_DATE       NUMBER(8),
  REGISTER_AGENT      NUMBER(10),
  CANCEL_DATE         NUMBER(8),
  CANCEL_AGENT        NUMBER(10),
  CONSTRAINT PK_OPERATOR PRIMARY KEY (OPERATOR_ID)
)
	';  
	END IF;
end;
/ 

/* 操作员子账户关联表 */
PROMPT
PROMPT create table OPERATORUNITMAP ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPERATORUNITMAP');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPERATORUNITMAP  (
  UNIT_ID             NUMBER(10) NOT NULL ,
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  DEFAULT_IS          CHAR(1) NOT NULL ,
  CONSTRAINT PK_OPERATORUNITMAP PRIMARY KEY (UNIT_ID,OPERATOR_ID,DEFAULT_IS)
)
	';  
	END IF;
end;
/ 

/* 操作日志表 */
PROMPT
PROMPT create table OPLOG ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPLOG');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPLOG  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  OPLOG_ID            NUMBER(10) NOT NULL ,
  TIME                NUMBER(6) NOT NULL ,
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  MENU_ID             NUMBER(10),
  TIMESTAMP           TIMESTAMP,
  OPTYPE_ID           NUMBER(10),
  OP_CONTENT          VARCHAR2(4000),
  CONSTRAINT PK_OPLOG PRIMARY KEY (OPLOG_ID)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISOPLOG ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISOPLOG');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISOPLOG  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  OPLOG_ID            NUMBER(10) NOT NULL ,
  TIME                NUMBER(6) NOT NULL ,
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  MENU_ID             NUMBER(10),
  TIMESTAMP           TIMESTAMP,
  OPTYPE_ID           NUMBER(10),
  OP_CONTENT          VARCHAR2(4000),
  CONSTRAINT PK_HISOPLOG PRIMARY KEY (BUSIN_DATE,OPLOG_ID)
)
	';  
	END IF;
end;
/ 

/* 人员菜单权限表 */
PROMPT
PROMPT create table OPRMENURIGHT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPRMENURIGHT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPRMENURIGHT  (
  ROLE_ID             NUMBER(10),
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  MENU_ID             NUMBER(10) NOT NULL ,
  MENU_RIGHTS         VARCHAR2(64),
  CONSTRAINT PK_OPRMENURIGHT PRIMARY KEY (ROLE_ID,OPERATOR_ID,MENU_ID)
)
	';  
	END IF;
end;
/ 


/* 人员账户权限表 */
PROMPT
PROMPT create table OPACCOUNTRIGHT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPACCOUNTRIGHT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPACCOUNTRIGHT  (
  ROLE_ID             NUMBER(10) NOT NULL ,
  OPERATOR_ID         NUMBER(10) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  UNIT_ID         		NUMBER(10) NOT NULL ,
  CONSTRAINT PK_OPACCOUNTRIGHT PRIMARY KEY (ROLE_ID,OPERATOR_ID,FUND_ID,UNIT_ID)
)
	';  
	END IF;
end;
/ 


/* 操作类型定义表 */
PROMPT
PROMPT create table OPTYPE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPTYPE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPTYPE  (
  OPTYPE_ID           NUMBER(8) NOT NULL ,
  OPTYPE_NAME         NUMBER(10) NOT NULL ,
  CONSTRAINT PK_OPTYPE PRIMARY KEY (OPTYPE_ID)
)
	'; 
	END IF; 
end;
/ 

/* 持仓限额表 */
PROMPT
PROMPT create table POSITIONLIMIT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('POSITIONLIMIT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE POSITIONLIMIT  (
  LIMIT_OBJECT        CHAR(1) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL ,
  FUND_ID             NUMBER(10) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  STOCK_RANGE         CHAR(1) NOT NULL ,
  STOCKTYPES          VARCHAR2(4000),
  STOCKCODES          VARCHAR2(4000),
  CIRCULATIONSTOCK_RATIO NUMBER(9,8),
  TOTALSTOCK_RATIO    NUMBER(9,8),
  PREMARKETVOL_RATIO  NUMBER(9,8),
  MAX_AMOUNT          NUMBER(10),
  MAX_COST            NUMBER(20,4),
  CONSTRAINT PK_POSITIONLIMIT PRIMARY KEY (LIMIT_OBJECT,INSTITUTION_ID,FUND_ID,UNIT_ID,STOCK_RANGE)
)
	';  
	END IF;
end;
/ 

/* 证券行情表 */
PROMPT
PROMPT create table QUOTE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('QUOTE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE QUOTE  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  STOP_FLAG           CHAR(1) NOT NULL ,
  OPEN_PRICE          NUMBER(16,8),
  YESTERDAY_CLOSEPRICE NUMBER(16,8),
  LAST_PRICE          NUMBER(16,8),
  UPLIMITED_PRICE     NUMBER(16,8),
  DOWNLIMITED_PRICE   NUMBER(16,8),
  AVG_PRICE           NUMBER(16,8),
  MAX_PRICE           NUMBER(16,8),
  MIN_PRICE           NUMBER(16,8),
  MARKET_DEAL_AMOUNT  NUMBER(16),
  MARKET_DEAL_BALANCE NUMBER(16,8),
  BUY_PRICE1          NUMBER(16,8),
  BUY_AMOUNT1         NUMBER(16),
  BUY_PRICE2          NUMBER(16,8),
  BUY_AMOUNT2         NUMBER(16),
  BUY_PRICE3          NUMBER(16,8),
  BUY_AMOUNT3         NUMBER(16),
  BUY_PRICE4          NUMBER(16,8),
  BUY_AMOUNT4         NUMBER(16),
  BUY_PRICE5          NUMBER(16,8),
  BUY_AMOUNT5         NUMBER(16),
  BUY_PRICE6          NUMBER(16,8),
  BUY_AMOUNT6         NUMBER(16),
  BUY_PRICE7          NUMBER(16,8),
  BUY_AMOUNT7         NUMBER(16),
  BUY_PRICE8          NUMBER(16,8),
  BUY_AMOUNT8         NUMBER(16),
  BUY_PRICE9          NUMBER(16,8),
  BUY_AMOUNT9         NUMBER(16),
  BUY_PRICE10         NUMBER(16,8),
  BUY_AMOUNT10        NUMBER(16),
  SALE_PRICE1         NUMBER(16,8),
  SALE_AMOUNT1        NUMBER(16),
  SALE_PRICE2         NUMBER(16,8),
  SALE_AMOUNT2        NUMBER(16),
  SALE_PRICE3         NUMBER(16,8),
  SALE_AMOUNT3        NUMBER(16),
  SALE_PRICE4         NUMBER(16,8),
  SALE_AMOUNT4        NUMBER(16),
  SALE_PRICE5         NUMBER(16,8),
  SALE_AMOUNT5        NUMBER(16),
  SALE_PRICE6         NUMBER(16,8),
  SALE_AMOUNT6        NUMBER(16),
  SALE_PRICE7         NUMBER(16,8),
  SALE_AMOUNT7        NUMBER(16),
  SALE_PRICE8         NUMBER(16,8),
  SALE_AMOUNT8        NUMBER(16),
  SALE_PRICE9         NUMBER(16,8),
  SALE_AMOUNT9        NUMBER(16),
  SALE_PRICE10        NUMBER(16,8),
  SALE_AMOUNT10       NUMBER(16),
  CONSTRAINT PK_QUOTE PRIMARY KEY (STOCK_CODE)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISQUOTE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISQUOTE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISQUOTE  (
  BUSIN_DATE          NUMBERR(8) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  STOP_FLAG           CHAR(1) NOT NULL ,
  OPEN_PRICE          NUMBER(16,8),
  YESTERDAY_CLOSEPRICE NUMBER(16,8),
  LAST_PRICE          NUMBER(16,8),
  UPLIMITED_PRICE     NUMBER(16,8),
  DOWNLIMITED_PRICE   NUMBER(16,8),
  AVG_PRICE           NUMBER(16,8),
  MAX_PRICE           NUMBER(16,8),
  MIN_PRICE           NUMBER(16,8),
  MARKET_DEAL_AMOUNT  NUMBER(16),
  MARKET_DEAL_BALANCE NUMBER(16,8),
  BUY_PRICE1          NUMBER(16,8),
  BUY_AMOUNT1         NUMBER(16),
  BUY_PRICE2          NUMBER(16,8),
  BUY_AMOUNT2         NUMBER(16),
  BUY_PRICE3          NUMBER(16,8),
  BUY_AMOUNT3         NUMBER(16),
  BUY_PRICE4          NUMBER(16,8),
  BUY_AMOUNT4         NUMBER(16),
  BUY_PRICE5          NUMBER(16,8),
  BUY_AMOUNT5         NUMBER(16),
  BUY_PRICE6          NUMBER(16,8),
  BUY_AMOUNT6         NUMBER(16),
  BUY_PRICE7          NUMBER(16,8),
  BUY_AMOUNT7         NUMBER(16),
  BUY_PRICE8          NUMBER(16,8),
  BUY_AMOUNT8         NUMBER(16),
  BUY_PRICE9          NUMBER(16,8),
  BUY_AMOUNT9         NUMBER(16),
  BUY_PRICE10         NUMBER(16,8),
  BUY_AMOUNT10        NUMBER(16),
  SALE_PRICE1         NUMBER(16,8),
  SALE_AMOUNT1        NUMBER(16),
  SALE_PRICE2         NUMBER(16,8),
  SALE_AMOUNT2        NUMBER(16),
  SALE_PRICE3         NUMBER(16,8),
  SALE_AMOUNT3        NUMBER(16),
  SALE_PRICE4         NUMBER(16,8),
  SALE_AMOUNT4        NUMBER(16),
  SALE_PRICE5         NUMBER(16,8),
  SALE_AMOUNT5        NUMBER(16),
  SALE_PRICE6         NUMBER(16,8),
  SALE_AMOUNT6        NUMBER(16),
  SALE_PRICE7         NUMBER(16,8),
  SALE_AMOUNT7        NUMBER(16),
  SALE_PRICE8         NUMBER(16,8),
  SALE_AMOUNT8        NUMBER(16),
  SALE_PRICE9         NUMBER(16,8),
  SALE_AMOUNT9        NUMBER(16),
  SALE_PRICE10        NUMBER(16,8),
  SALE_AMOUNT10       NUMBER(16),
  CONSTRAINT PK_HISQUOTE PRIMARY KEY (BUSIN_DATE,STOCK_CODE)
)
	';  
	END IF;
end;
/ 

/* 角色表 */
PROMPT
PROMPT create table ROLE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('ROLE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE ROLE  (
  ROLE_ID             NUMBER(10) NOT NULL ,
  ROLE_NAME           VARCHAR2(16) NOT NULL ,
  INSTITUTION_ID      NUMBER(10) NOT NULL,
  REMARK              VARCHAR2(256),
  CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID)
)
	';  
	END IF;
end;
/ 

/* 操作员角色表*/
PROMPT
PROMPT create table OPROLES ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('OPROLES');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE OPROLES(
  OPERATOR_ID         NUMBER(10) NOT NULL,
  ROLE_ID             NUMBER(10) NOT NULL ,  
  CONSTRAINT PK_OPROLES PRIMARY KEY (OPERATOR_ID,ROLE_ID)
)
	';  
	END IF;
end;
/ 


/* 证券资料表 */
PROMPT
PROMPT create table STOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('STOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE STOCK  (
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  MARKET_CODE         NUMBER(4),
  REPORT_CODE         VARCHAR2(32) NOT NULL ,
  STOCK_NAME          VARCHAR2(100),
  STOCK_SPELL         VARCHAR2(4),
  STOCK_FULLNAME      VARCHAR2(256),
  STOCKTYPE_CODE      NUMBER(4),
  UPLIMITED_RATIO     NUMBER(16,8),
  DOWNLIMITED_RATIO   NUMBER(16,8),
  TRADE_CURRENCY_NO   CHAR(3),
  FACE_VALUES         NUMBER(16,8),
  CIRCULATIONSTOCK_AMOUNT NUMBER(16),
  TOTALSTOCK_AMOUNT   NUMBER(16),
  ONMARKET_DATE       NUMBER(8),
  STATUS              CHAR(1),
  CONSTRAINT PK_STOCK PRIMARY KEY (STOCK_CODE)
)
	'; 
	END IF; 
end;
/ 

/* 证券类别表 */
PROMPT
PROMPT create table STOCKTYPE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('STOCKTYPE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE STOCKTYPE  (
  STOCKTYPE_CODE      NUMBER(4) NOT NULL ,
  STOCKTYPE_NAME      VARCHAR2(16) NOT NULL ,  
  AMOUNT_PER_HAND      NUMBER(10) NOT NULL ,
  PRICE_INTERVAL      NUMBER(16,8) NOT NULL ,
  BUY_UNIT            NUMBER(10) NOT NULL ,
  SALE_UNIT           NUMBER(10) NOT NULL ,
  BUY_MAX             NUMBER(10) NOT NULL ,
  SALE_MAX            NUMBER(10) NOT NULL ,
  CONSTRAINT PK_STOCKTYPE PRIMARY KEY (STOCKTYPE_CODE)
)
	';  
	END IF;
end;
/ 

/* 系统信息表 */
PROMPT
PROMPT create table SYSTEMINFO ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('SYSTEMINFO');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE SYSTEMINFO  (
  SERVICEPROVIDER_CODE VARCHAR2(16) NOT NULL ,
  SERVICEPROVIDER_NAME VARCHAR2(32) NOT NULL ,
  PRODUCT_CODE        VARCHAR2(16) NOT NULL ,
  PRODUCT_NAME        VARCHAR2(32) NOT NULL ,
  PRODUCT_VERSION     VARCHAR2(16) NOT NULL ,
  PREBUSIN_DATE       NUMBER(8) NOT NULL ,
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  CONSTRAINT PK_TSYSTEMINFO PRIMARY KEY (SERVICEPROVIDER_CODE)
)
	';  
	END IF;
end;
/ 

/* 子账户资金表 */
PROMPT
PROMPT create table UNITASSET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('UNITASSET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE UNITASSET  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  CURRENCY_CODE       CHAR(3) NOT NULL ,
  BEGIN_CASH          NUMBER(20,4) NOT NULL ,
  CURRENT_CASH        NUMBER(20,4) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PREBUY_FEE          NUMBER(20,4) NOT NULL ,
  PRESALE_FEE          NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  INPUT_BALANCE       NUMBER(20,4) NOT NULL ,
  OUTPUT_BALANCE      NUMBER(20,4) NOT NULL ,
  INPUT_TOTAL         NUMBER(20,4) NOT NULL ,
  OUTPUT_TOTAL        NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_UNITASSET PRIMARY KEY (UNIT_ID,CURRENCY_CODE)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISUNITASSET ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISUNITASSET');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISUNITASSET  (
  BUSIN_DATE          NUMBER(8) NOT NULL ,
  UNIT_ID             NUMBER(10) NOT NULL ,
  CURRENCY_CODE       CHAR(3) NOT NULL ,
  BEGIN_CASH          NUMBER(20,4) NOT NULL ,
  CURRENT_CASH        NUMBER(20,4) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  INPUT_BALANCE       NUMBER(20,4) NOT NULL ,
  OUTPUT_BALANCE      NUMBER(20,4) NOT NULL ,
  INPUT_TOTAL         NUMBER(20,4) NOT NULL ,
  OUTPUT_TOTAL        NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_HISUNITASSET PRIMARY KEY (BUSIN_DATE,UNIT_ID,CURRENCY_CODE)
)
	';  
	END IF;
end;
/ 

/* 子账户股份表 */
PROMPT
PROMPT create table UNITSTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('UNITSTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE UNITSTOCK  (
  BUSIN_DATE          NUMBER(8),
  UNIT_ID             NUMBER(10) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_BUYFEE  NUMBER(20,4),
  BEGIN_TOTAL_SALEFEE NUMBER(20,4),
  CURRENT_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_AMOUNT       NUMBER(16) NOT NULL ,
  PRESALE_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  BUY_AMOUNT          NUMBER(16) NOT NULL ,
  SALE_AMOUNT         NUMBER(16) NOT NULL ,
  BUY_BALANCE         NUMBER(20,4) NOT NULL ,
  SALE_BALANCE        NUMBER(20,4) NOT NULL ,
  BUY_FEE             NUMBER(20,4) NOT NULL ,
  SALE_FEE            NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_UNITSTOCK PRIMARY KEY (UNIT_ID,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 

PROMPT
PROMPT create table HISUNITSTOCK ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('HISUNITSTOCK');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
  CREATE TABLE HISUNITSTOCK  (
  BUSIN_DATE          NUMBER(8),
  UNIT_ID             NUMBER(10) NOT NULL ,
  STOCK_CODE          VARCHAR2(32) NOT NULL ,
  BS                  CHAR(1) NOT NULL ,
  BEGIN_AMOUNT        NUMBER(16) NOT NULL ,
  BEGIN_COST          NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_PROFIT  NUMBER(20,4) NOT NULL ,
  BEGIN_TOTAL_BUYFEE  NUMBER(20,4),
  BEGIN_TOTAL_SALEFEE NUMBER(20,4),
  CURRENT_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_AMOUNT       NUMBER(16) NOT NULL ,
  PRESALE_AMOUNT      NUMBER(16) NOT NULL ,
  PREBUY_BALANCE      NUMBER(20,4) NOT NULL ,
  PRESALE_BALANCE     NUMBER(20,4) NOT NULL ,
  BUY_AMOUNT          NUMBER(16) NOT NULL ,
  SALE_AMOUNT         NUMBER(16) NOT NULL ,
  BUY_BALANCE         NUMBER(20,4) NOT NULL ,
  SALE_BALANCE        NUMBER(20,4) NOT NULL ,
  BUY_FEE             NUMBER(20,4) NOT NULL ,
  SALE_FEE            NUMBER(20,4) NOT NULL ,
  CONSTRAINT PK_HISUNITSTOCK PRIMARY KEY (BUSIN_DATE,UNIT_ID,STOCK_CODE,BS)
)
	';  
	END IF;
end;
/ 


/* 股东账户表 */
PROMPT
PROMPT create table STOCKHOLDER ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('STOCKHOLDER');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
CREATE TABLE STOCKHOLDER 
(
   MARKET_CODE          NUMBER(4)                      NOT NULL,
   STOCKHOLDER_CODE     VARCHAR2(64)                   NOT NULL,
   INVEST_TYPE          CHAR(1)                        NOT NULL,
   FUND_ID              NUMBER(10)                     NOT NULL,
   REMARK               VARCHAR2(256)                  NULL,
   CONSTRAINT PK_STOCKHOLDER PRIMARY KEY (MARKET_CODE, STOCKHOLDER_CODE)
)

	';  
	END IF;
end;
/ 

/* 资金账户表 */
PROMPT
PROMPT create table CASHACCOUNT ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('CASHACCOUNT');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
CREATE TABLE CASHACCOUNT 
(
   CASHACCOUNT_CODE     VARCHAR2(64)                   NOT NULL,
   MARKET_SCOPE         VARCHAR2(4000)                 NOT NULL,
   FUND_ID              NUMBER(10)                     NOT NULL,
   REMARK               VARCHAR2(256)                  NULL,
   CONSTRAINT PK_CASHACCOUNT PRIMARY KEY (CASHACCOUNT_CODE)
)
	';  
	END IF;
end;
/ 


/* 自定义序列表 */
PROMPT
PROMPT create table CUSTOMSEQUENCE ，if not exist then create......
DECLARE
  rowcount NUMBER;
begin
  SELECT COUNT(1) INTO rowcount FROM USER_TABLES WHERE TABLE_NAME = upper('CUSTOMSEQUENCE');
  IF rowcount = 0 THEN
  	EXECUTE IMMEDIATE '
CREATE TABLE CUSTOMSEQUENCE 
(
   CUSTOMSEQ_ID              NUMBER(10)                NOT NULL,
   CUSTOMSEQ_NAME            VARCHAR2(32)              NOT NULL,   
   INITIAL_VALUE             NUMBER(20)                NOT NULL,
   MAX_VALUE	               NUMBER(20)                NOT NULL,
   CURRENT_VALUE	           NUMBER(20)                NOT NULL,
   STATUS                    CHAR(1)                   NOT NULL,
   CONSTRAINT PK_CUSTOMSEQUENCE PRIMARY KEY (CUSTOMSEQ_ID)
)
	';  
	END IF;
end;
/ 


DECLARE
  rowcount NUMBER;
BEGIN	
  SELECT COUNT(1) INTO rowcount FROM CUSTOMSEQUENCE WHERE CUSTOMSEQ_ID = 1;
  IF rowcount = 0 THEN
    INSERT INTO CUSTOMSEQUENCE(CUSTOMSEQ_ID,CUSTOMSEQ_NAME,INITIAL_VALUE,MAX_VALUE,CURRENT_VALUE,STATUS)
    VALUES(1,'委托批号',1,1000000000,0,'1');
	END IF;
	
	SELECT COUNT(1) INTO rowcount FROM CUSTOMSEQUENCE WHERE CUSTOMSEQ_ID = 2;
  IF rowcount = 0 THEN
    INSERT INTO CUSTOMSEQUENCE(CUSTOMSEQ_ID,CUSTOMSEQ_NAME,INITIAL_VALUE,MAX_VALUE,CURRENT_VALUE,STATUS)
    VALUES(2,'委托序号',1,1000000000,0,'1');
	END IF;
END;
/
	

DECLARE
  rowcount NUMBER;
BEGIN	
	/*成交序号*/
	SELECT COUNT(1) INTO rowcount FROM USER_SEQUENCES WHERE SEQUENCE_NAME = upper('SEQ_BUSINESS_ID');
	IF rowcount = 0 THEN
	  EXECUTE IMMEDIATE '
	  CREATE SEQUENCE SEQ_BUSINESS_ID 
	     INCREMENT BY 1 
	     START WITH 1 
	     MAXVALUE 1000000000 
	     CYCLE 
	     CACHE 10
	  ';
	END IF;	
	
	/*资金流水批号*/
	SELECT COUNT(1) INTO rowcount FROM USER_SEQUENCES WHERE SEQUENCE_NAME = upper('SEQ_CASHFLOW_BATCHID');
	IF rowcount = 0 THEN
	  EXECUTE IMMEDIATE '
	  CREATE SEQUENCE SEQ_CASHFLOW_BATCHID 
	     INCREMENT BY 1 
	     START WITH 1 
	     MAXVALUE 1000000000 
	     CYCLE 
	     CACHE 10
	  ';
	END IF;
		
	/*资金流水序号*/
	SELECT COUNT(1) INTO rowcount FROM USER_SEQUENCES WHERE SEQUENCE_NAME = upper('SEQ_CASHFLOW_ID');
	IF rowcount = 0 THEN
	  EXECUTE IMMEDIATE '
	  CREATE SEQUENCE SEQ_CASHFLOW_ID 
	     INCREMENT BY 1 
	     START WITH 1 
	     MAXVALUE 1000000000 
	     CYCLE 
	     CACHE 10
	  ';
	END IF;	
	
	/*操作日志流水号*/
	SELECT COUNT(1) INTO rowcount FROM USER_SEQUENCES WHERE SEQUENCE_NAME = upper('SEQ_OPLOG_ID');
	IF rowcount = 0 THEN
	  EXECUTE IMMEDIATE '
	  CREATE SEQUENCE SEQ_OPLOG_ID 
	     INCREMENT BY 1 
	     START WITH 1 
	     MAXVALUE 1000000000 
	     CYCLE 
	     CACHE 10
	  ';
	END IF;		
END;	
/

COMMIT;
PROMPT create all tables end...